/** All admin UI copy (English only: the panel is internal). */
export const copy = {
  brand: "COLD FORGE",
  product: "Admin",
  nav: { dashboard: "Dashboard", users: "Users", audit: "Audit log" },

  signIn: {
    title: "Admin console",
    body: "Restricted area. Sign in with the Google account that holds admin rights.",
    button: "Sign in with Google",
    working: "Waiting for Google…",
    denied: (email?: string) =>
      email ? `${email} is not authorized. You have been signed out.` : "Not authorized. You have been signed out.",
    deniedTitle: "Not authorized",
    expired: "Your session was revoked or expired. Sign in again.",
    idle: "Signed out after 30 minutes of inactivity.",
    error: "Sign-in failed. Try again.",
    popupBlocked: "The sign-in popup was blocked. Allow popups for this site and try again.",
    footer: "Every action is recorded in the audit log.",
  },

  session: { signOut: "Sign out", signedInAs: "Signed in as" },

  dashboard: {
    title: "Dashboard",
    subtitle: "Live numbers from Auth and Firestore.",
    refresh: "Refresh",
    totalUsers: "Total users",
    signups7d: "Sign-ups · 7 days",
    signups30d: "Sign-ups · 30 days",
    active7d: "Active · 7 days",
    activeHint: "profile updated in the last week",
    disabled: "Disabled",
    admins: "Admins",
    arcs: "Arcs",
    habits: "Habits",
    checkIns: "Check-ins",
    capped: "Account scan hit its cap; user numbers are lower bounds.",
    generated: (when: string) => `Generated ${when}`,
    accounts: "Accounts",
    content: "Content",
  },

  users: {
    title: "Users",
    subtitle: "Search by exact email, or any part of an email or name.",
    searchPlaceholder: "Search email, name or uid",
    search: "Search",
    clear: "Clear",
    columns: {
      user: "User",
      providers: "Providers",
      created: "Created",
      lastSignIn: "Last sign-in",
      status: "Status",
    },
    empty: "No users match.",
    loadMore: "Load more",
    scanned: (n: number) => `Scanned ${n.toLocaleString("en")} accounts.`,
    exact: "Exact match.",
    truncated: "Too many matches; showing the first 100. Refine the query.",
    active: "Active",
    disabled: "Disabled",
    admin: "Admin",
    unverified: "Unverified",
    noEmail: "(no email)",
    noName: "—",
  },

  detail: {
    close: "Close",
    profile: "Profile",
    account: "Account",
    data: "Data",
    uid: "UID",
    email: "Email",
    verified: "verified",
    notVerified: "not verified",
    providers: "Providers",
    created: "Created",
    lastSignIn: "Last sign-in",
    lastRefresh: "Last token refresh",
    displayName: "Display name",
    locale: "Locale",
    currentArc: "Current arc",
    updated: "Profile updated",
    noProfile: "No profile document (user never synced).",
    actions: "Actions",
    disable: "Disable account",
    enable: "Enable account",
    makeAdmin: "Make admin",
    removeAdmin: "Remove admin",
    delete: "Delete account and data",
    selfNote: "This is your account. You cannot disable, delete or change admin rights on yourself.",
    adminNote: "Admins can't be disabled or deleted. Remove admin rights first.",
    copy: "Copy",
    copied: "Copied",
  },

  dialogs: {
    cancel: "Cancel",
    reasonLabel: "Reason (recorded in the audit log)",
    reasonPlaceholder: "e.g. spam reports, user request #123",
    reasonHint: "3–500 characters.",
    disableTitle: "Disable account",
    disableBody: (email: string) =>
      `${email} will be signed out everywhere and can't sign in or sync until re-enabled. Their data is kept.`,
    disableConfirm: "Disable",
    enableTitle: "Enable account",
    enableBody: (email: string) => `${email} will be able to sign in again.`,
    enableConfirm: "Enable",
    grantTitle: "Grant admin rights",
    grantBody: (email: string) =>
      `${email} will be able to see every user and disable or delete accounts. Only do this for people you fully trust.`,
    grantConfirm: "Make admin",
    revokeTitle: "Remove admin rights",
    revokeBody: (email: string) => `${email} loses admin access immediately and is signed out of all sessions.`,
    revokeConfirm: "Remove admin",
    deleteTitle: "Delete account permanently",
    deleteBody: "This deletes the Firebase account and every arc, habit and check-in. It cannot be undone.",
    deleteTypeLabel: (email: string) => `Type ${email} to confirm`,
    deleteConfirm: "Delete forever",
    reauthTitle: "Confirm it's you",
    reauthBody: "This action needs a fresh sign-in (older than 30 minutes). Sign in with Google again to continue.",
    reauthConfirm: "Re-authenticate",
  },

  audit: {
    title: "Audit log",
    subtitle: "Every admin mutation (including refused attempts) and every single-account view, newest first. Written only by Cloud Functions.",
    when: "When",
    actor: "Actor",
    action: "Action",
    target: "Target",
    reason: "Reason",
    outcome: "Outcome",
    empty: "No admin actions recorded yet.",
    loadMore: "Load more",
    actions: {
      "user.view": "Viewed",
      "user.disable": "Disabled",
      "user.enable": "Enabled",
      "user.delete": "Deleted",
      "admin.grant": "Granted admin",
      "admin.revoke": "Removed admin",
      unknown: "Unknown",
    },
    ok: "ok",
    error: "failed",
    refused: "refused",
  },

  toasts: {
    disabled: "Account disabled.",
    enabled: "Account enabled.",
    deleted: "Account and data deleted.",
    granted: "Admin rights granted.",
    revoked: "Admin rights removed.",
  },

  errors: {
    generic: "Something went wrong. Try again.",
    retry: "Retry",
    rateLimited: "Too many requests. Wait a minute.",
    notConfigured: "Admin access isn't configured on the server: set the ADMIN_ALLOWED_EMAILS secret (see apps/functions/README.md).",
    byCode: {
      "invalid-argument": "Invalid input.",
      "not-found": "That user no longer exists.",
      "permission-denied": "Not authorized.",
      unauthenticated: "Your session expired.",
      "failed-precondition": "This action isn't allowed right now.",
      "resource-exhausted": "Too many requests. Wait a minute.",
      aborted: "Your admin rights changed during this action. Nothing was changed.",
      internal: "Server error. Try again.",
      unavailable: "Service unavailable. Try again.",
      "deadline-exceeded": "The request timed out.",
    } as Record<string, string>,
  },

} as const;
