import type { HabitTemplateId, ISODate } from "@cold-forge/core";
import type { Locale } from "@cold-forge/i18n";

/**
 * Wire format shared by the app and the API. Every record is merged with last-write-wins on
 * `updatedAt` (ISO timestamp). Deletions are tombstones (`deletedAt`), never hard deletes,
 * so they propagate to other devices.
 *
 * IDs are generated by clients. The server MUST scope every record by the authenticated user,
 * so two users sending the same id never touch each other's data.
 */
export const SYNC_PROTOCOL_VERSION = 1;

export interface SyncArc {
  id: string;
  kind: "winter" | "custom";
  startDate: ISODate;
  endDate: ISODate;
  why: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
}

export interface SyncHabit {
  id: string;
  arcId: string;
  templateId?: HabitTemplateId;
  name: string;
  emoji: string;
  order: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
}

/** Identified by (habitId, date). `done: false` is how an un-check propagates. */
export interface SyncCheckIn {
  habitId: string;
  date: ISODate;
  done: boolean;
  updatedAt: string;
}

/** Account-level settings that follow the user across devices (device prefs like sound stay local). */
export interface SyncProfile {
  displayName: string;
  locale: Locale;
  /** The arc the user is currently forging; other arcs are history. */
  currentArcId: string | null;
  updatedAt: string;
}

export interface SyncChanges {
  arcs: SyncArc[];
  habits: SyncHabit[];
  checkIns: SyncCheckIn[];
  profile: SyncProfile | null;
}

/** `POST /v1/sync` body. `cursor` is the opaque value from the previous response (null on first sync). */
export interface SyncRequest {
  protocol: typeof SYNC_PROTOCOL_VERSION;
  cursor: string | null;
  changes: SyncChanges;
}

/** Everything that changed on the server after `cursor` (including what this request just wrote). */
export interface SyncResponse {
  protocol: typeof SYNC_PROTOCOL_VERSION;
  cursor: string;
  changes: SyncChanges;
  serverTime: string;
}

export interface AuthUser {
  id: string;
  email: string;
}

/** `POST /v1/auth/magic-link` body. The response is always 202 `{ requestId }`, whether or not the email exists. */
export interface MagicLinkRequest {
  email: string;
  locale: Locale;
}

/** `POST /v1/auth/verify` body: either the 6-digit code typed in the app, or the token from the emailed link. */
export type VerifyRequest = { requestId: string; code: string } | { token: string };

export interface SessionResponse {
  /** Opaque bearer token. Send as `Authorization: Bearer <token>`. */
  token: string;
  expiresAt: string;
  user: AuthUser;
}
