import type { HabitTemplateId, ISODate } from "@cold-forge/core";
import type { Locale } from "@cold-forge/i18n";

/**
 * Wire format shared by the app and the API. Every record is merged with last-write-wins on
 * `updatedAt` (ISO timestamp). Deletions are tombstones (`deletedAt`), never hard deletes,
 * so they propagate to other devices.
 *
 * IDs are generated by clients. The server MUST scope every record by the authenticated user,
 * so two users sending the same id never touch each other's data.
 */
export const SYNC_PROTOCOL_VERSION = 1;

export interface SyncArc {
  id: string;
  kind: "winter" | "custom";
  startDate: ISODate;
  endDate: ISODate;
  why: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
}

export interface SyncHabit {
  id: string;
  arcId: string;
  templateId?: HabitTemplateId;
  name: string;
  emoji: string;
  order: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
}

/** Identified by (habitId, date). `done: false` is how an un-check propagates. */
export interface SyncCheckIn {
  habitId: string;
  date: ISODate;
  done: boolean;
  updatedAt: string;
}

/** Account-level settings that follow the user across devices (device prefs like sound stay local). */
export interface SyncProfile {
  displayName: string;
  locale: Locale;
  /** The arc the user is currently forging; other arcs are history. */
  currentArcId: string | null;
  updatedAt: string;
}

export interface SyncChanges {
  arcs: SyncArc[];
  habits: SyncHabit[];
  checkIns: SyncCheckIn[];
  profile: SyncProfile | null;
}

/** `POST /v1/sync` body. `cursor` is the opaque value from the previous response (null on first sync). */
export interface SyncRequest {
  protocol: typeof SYNC_PROTOCOL_VERSION;
  cursor: string | null;
  changes: SyncChanges;
}

/**
 * Everything that changed on the server after `cursor` (including what this request just wrote).
 * The cursor is opaque. While `hasMore` is true, call again with the returned cursor and empty changes.
 * A `400 invalid_cursor` means the client should reset its cursor to null and sync again.
 */
export interface SyncResponse {
  protocol: typeof SYNC_PROTOCOL_VERSION;
  cursor: string;
  changes: SyncChanges;
  hasMore: boolean;
  serverTime: string;
}

/** `GET /v1/export`: every record the server holds for the user, tombstones included. */
export interface ExportResponse extends SyncChanges {
  exportedAt: string;
  user: AuthUser;
}

export type ApiErrorCode =
  | "invalid_or_expired"
  | "invalid_email"
  | "invalid_request"
  | "invalid_cursor"
  | "quota_exceeded"
  | "rate_limited"
  | "unauthorized"
  | "unsupported_media_type"
  | "payload_too_large"
  | "origin_not_allowed"
  | "not_found"
  | "method_not_allowed"
  | "internal_error";

/** Every non-2xx response body. `detail` only ever names fields, never echoes values. */
export interface ApiError {
  error: ApiErrorCode;
  detail?: string;
}

export interface AuthUser {
  id: string;
  email: string;
}

/** `POST /v1/auth/magic-link` body. The response is always 202 `{ requestId }`, whether or not the email exists. */
export interface MagicLinkRequest {
  email: string;
  locale: Locale;
}

/** `POST /v1/auth/verify` body: either the 6-digit code typed in the app, or the token from the emailed link. */
export type VerifyRequest = { requestId: string; code: string } | { token: string };

export interface SessionResponse {
  /** Opaque bearer token. Send as `Authorization: Bearer <token>`. */
  token: string;
  expiresAt: string;
  user: AuthUser;
}
