/**
 * SQLite schema and migrations (bun:sqlite).
 *
 * - `PRAGMA user_version` is the schema version; `MIGRATIONS[i]` upgrades from version i to i+1.
 *   Append new migrations, never edit old ones.
 * - Every user-owned table is keyed by `(user_id, …)` because ids are generated by clients and
 *   may collide across users. Every query in this codebase filters by the authenticated user id.
 * - Codes, link tokens and session tokens are stored only as HMAC-SHA256 digests (BLOB).
 * - Times owned by the server are epoch milliseconds (INTEGER); client timestamps stay ISO TEXT.
 */
import { Database } from "bun:sqlite";
import { chmodSync, existsSync } from "node:fs";

const MIGRATIONS: readonly string[] = [
  /* 0 → 1 */ `
  CREATE TABLE users (
    id          TEXT    NOT NULL PRIMARY KEY,
    email       TEXT    NOT NULL UNIQUE,
    created_at  INTEGER NOT NULL,
    -- Per-user monotonically increasing change counter; every synced write takes the next value.
    seq         INTEGER NOT NULL DEFAULT 0 CHECK (seq >= 0)
  ) STRICT;

  CREATE TABLE login_requests (
    id          TEXT    NOT NULL PRIMARY KEY,
    email       TEXT    NOT NULL,
    code_hash   BLOB    NOT NULL,
    token_hash  BLOB    NOT NULL UNIQUE,
    attempts    INTEGER NOT NULL DEFAULT 0,
    created_at  INTEGER NOT NULL,
    expires_at  INTEGER NOT NULL
  ) STRICT;
  CREATE INDEX login_requests_email ON login_requests (email);
  CREATE INDEX login_requests_expires ON login_requests (expires_at);

  CREATE TABLE sessions (
    token_hash    BLOB    NOT NULL PRIMARY KEY,
    user_id       TEXT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at    INTEGER NOT NULL,
    expires_at    INTEGER NOT NULL,
    last_used_at  INTEGER NOT NULL
  ) STRICT;
  CREATE INDEX sessions_user ON sessions (user_id);
  CREATE INDEX sessions_expires ON sessions (expires_at);

  CREATE TABLE arcs (
    user_id     TEXT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    id          TEXT    NOT NULL,
    kind        TEXT    NOT NULL CHECK (kind IN ('winter', 'custom')),
    start_date  TEXT    NOT NULL,
    end_date    TEXT    NOT NULL,
    why         TEXT    NOT NULL,
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL,
    deleted_at  TEXT,
    seq         INTEGER NOT NULL,
    PRIMARY KEY (user_id, id)
  ) STRICT;
  CREATE INDEX arcs_seq ON arcs (user_id, seq);

  CREATE TABLE habits (
    user_id      TEXT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    id           TEXT    NOT NULL,
    arc_id       TEXT    NOT NULL,
    template_id  TEXT,
    name         TEXT    NOT NULL,
    emoji        TEXT    NOT NULL,
    sort_order   INTEGER NOT NULL,
    created_at   TEXT    NOT NULL,
    updated_at   TEXT    NOT NULL,
    deleted_at   TEXT,
    seq          INTEGER NOT NULL,
    PRIMARY KEY (user_id, id)
  ) STRICT;
  CREATE INDEX habits_seq ON habits (user_id, seq);

  CREATE TABLE check_ins (
    user_id     TEXT    NOT NULL,
    habit_id    TEXT    NOT NULL,
    date        TEXT    NOT NULL,
    done        INTEGER NOT NULL CHECK (done IN (0, 1)),
    updated_at  TEXT    NOT NULL,
    seq         INTEGER NOT NULL,
    PRIMARY KEY (user_id, habit_id, date),
    -- A check-in can only point at a habit of the SAME user.
    FOREIGN KEY (user_id, habit_id) REFERENCES habits (user_id, id) ON DELETE CASCADE
  ) STRICT;
  CREATE INDEX check_ins_seq ON check_ins (user_id, seq);

  CREATE TABLE profiles (
    user_id         TEXT    NOT NULL PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    display_name    TEXT    NOT NULL,
    locale          TEXT    NOT NULL,
    current_arc_id  TEXT,
    updated_at      TEXT    NOT NULL,
    seq             INTEGER NOT NULL
  ) STRICT;
  CREATE INDEX profiles_seq ON profiles (user_id, seq);
  `,
  /* 1 → 2 */ `
  -- Wrong login codes per email, across requests (online guessing cap). A fixed 24 h window that
  -- starts at the first failure; a successful sign-in deletes the row.
  CREATE TABLE verify_failures (
    email         TEXT    NOT NULL PRIMARY KEY,
    failures      INTEGER NOT NULL CHECK (failures >= 0),
    window_start  INTEGER NOT NULL
  ) STRICT;
  `,
];

export const SCHEMA_VERSION = MIGRATIONS.length;

/** Opens (or creates) the database, applies pragmas and pending migrations. Use ":memory:" in tests. */
export function openDatabase(path: string): Database {
  // strict: named parameters bind without a prefix and a missing parameter throws.
  const db = new Database(path, { create: true, strict: true });
  db.exec("PRAGMA journal_mode = WAL"); // no-op for :memory:
  db.exec("PRAGMA foreign_keys = ON");
  db.exec("PRAGMA busy_timeout = 5000");
  db.exec("PRAGMA synchronous = NORMAL");
  // Overwrite deleted content so an account deletion does not leave data in free pages.
  db.exec("PRAGMA secure_delete = ON");
  migrate(db);
  restrictDatabaseFiles(path);
  return db;
}

/** chmod 600 the database and its WAL/SHM side files (they hold user data and login digests). */
export function restrictDatabaseFiles(path: string): void {
  if (path === ":memory:" || path === "" || path.startsWith("file:")) return;
  for (const file of [path, `${path}-wal`, `${path}-shm`]) {
    try {
      if (existsSync(file)) chmodSync(file, 0o600);
    } catch {
      // Not fatal (e.g. a read-only mount); the umask still applies to new files.
    }
  }
}

export function migrate(db: Database): void {
  const current = (db.query("PRAGMA user_version").get() as { user_version: number }).user_version;
  if (current > MIGRATIONS.length) {
    throw new Error(`Database schema v${current} is newer than this build (v${MIGRATIONS.length})`);
  }
  for (let v = current; v < MIGRATIONS.length; v++) {
    db.transaction(() => {
      db.exec(MIGRATIONS[v]!);
      // PRAGMA cannot take bound parameters; `v + 1` is a trusted integer from this loop.
      db.exec(`PRAGMA user_version = ${Number(v + 1)}`);
    })();
  }
  const fk = db.query("PRAGMA foreign_keys").get() as { foreign_keys: number };
  if (fk.foreign_keys !== 1) throw new Error("SQLite foreign keys could not be enabled");
}
